### ISSUE TITLE
world rename

### ISSUE THREAD

**Issue by mercadanteus** [innc11/PepperShop#2]
After rename my world hundred of shops stopped working, I tried to replace in bulk the old world name with the new one in the shops yml file, and change the file name from world.yml to world1.yml.   I thougt it was enought but didn´t work, could you suggest me a solution, thank you very much.

**Comment by innc11** [comment]
Could you see the loading messages of each world on the console like above when Nukkit started up?

![image](https://user-images.githubusercontent.com/28993050/109585990-66a24a00-7b3f-11eb-830f-18ce2f704481.png)

**Comment by mercadanteus** [comment]
Hello, The problematic world is "world1" (previously "world"), It contain 985 shops affected, made before the world name change and that I tried to repair as I said in previous messages, and 95 shops that are ok, made after the name change.  Apparently all shops are loaded, but those 985 don't work

2021-03-01 17:01:32.200 [main] INFO  - [PepperShop] Loaded §619§r shops from the §bcastleworld
2021-03-01 17:01:32.449 [main] INFO  - [PepperShop] Loaded §61082§r shops from the §bworld1
2021-03-01 17:01:32.450 [main] INFO  - [PepperShop] Loaded §60§r shops from the §bworld2
2021-03-01 17:01:32.477 [main] INFO  - [PepperShop] Loaded §6126§r shops from the §bmercado
2021-03-01 17:01:32.479 [main] INFO  - [PepperShop] Loaded §60§r shops from the §bnether

**Comment by innc11** [comment]
Have the directory name of the world been changed yet? I think this may be where the problem lies.
Because the program only reads the world-name from the folder simply, not from its binary.

**Comment by mercadanteus** [comment]
I discovered the error, while renaming the shops, I did the first line but I fogot to rename the string above the "shopRandomId" line. Thank you very much, Its a wonderful plugin

**Comment by innc11** [comment]
Happy to help 😄
